
 version: '3'
 services:
   strapi:
     build: .
     image: my-strapi:0.0.6
     env_file: ../my-strapi-v4/.env
     environment:
       DATABASE_CLIENT: mysql
       DATABASE_HOST: mysql
       DATABASE_PORT: 3306
       DATABASE_NAME: strapi
       DATABASE_USERNAME: phoenix
       DATABASE_PASSWORD: 033586567
       DATABASE_SSL: 'false'
       TZ: Asia/Taipei
     links: 
       - mysql:mysql
     volumes:
       - ../my-strapi-v4/config:/opt/app/config
       - ../my-strapi-v4/src:/opt/app/src
       - ../my-strapi-v4/package.json:/opt/package.json
       - ../my-strapi-v4/yarn.lock:/opt/yarn.lock
       - ../my-strapi-v4/.env:/opt/app/.env
       - /etc/timezone:/etc/timezone:ro
       - /etc/localtime:/etc/localtime:ro
     ports:
       - '1337:1337'
     depends_on:
       - mysql

   mysql:
     image: mysql:latest
     command: mysqld --default-authentication-plugin=mysql_native_password
     volumes:
       - ./mysql-dev:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: 1qaz@WSX
       MYSQL_DATABASE: strapi
       MYSQL_USER: phoenix
       MYSQL_PASSWORD: 033586567
     ports:
       - '3306:3306'

   webserver:
     image: nginx:latest
     ports:
       - '80:80'
       - '443:443'
     restart: always
     extra_hosts:
       - "host.docker.internal:host-gateway"
     volumes:
       - ./nginx/conf/:/etc/nginx/conf.d/:ro
       - ./dist/:/usr/share/nginx/html/dist/:ro
       - ./certbot/www:/var/www/certbot:ro
       - ./certbot/conf:/etc/nginx/ssl:ro
